# The configuration file provides values for the two, differential
# drive motors, 'm1' and 'm2'. See the article: 
# https://resources.basicmicro.com/auto-tuning-with-motion-studio/
# for a description of how to derive the p, i, d and qpps values.

motor_driver_node:
  ros__parameters:
    # Incremental acceleration to use in quadrature pulses per second.
 
    accel_quad_pulses_per_second: 4500

    # The device name to be opened.
    #device_name: "/dev/roboclaw"
    device_name: "/dev/ttyACM0"

    # The assigned port for the device (as configured on the RoboClaw).
    device_port: 128

    # The P, I, D and maximum quadrature pulses per second for both motors.


    m1_p: 1.95074
    m1_i: 0.28177
    m1_d: 0.0
    m1_qpps: 9562
    m2_p: 2.00313
    m2_i: 0.29676
    m2_d: 0.0
    m2_qpps: 9375


    # The maximum expected current (in amps) for both motors.
    # Used just to signal warnings.
    m1_max_current: 15
    m2_max_current: 15
  

    # Rate limiting commands. The driver will clip any value
    # exceeding these limits.
    max_angular_velocity: 0.07 # m/s
    max_linear_velocity: 0.3 # rad/s

    # If no new motor commands is received since the last motor
    # command in this number of seconds, stop the motors.
    max_seconds_uncommanded_travel: 0.25 # seconds

    # NB! There is a bug and not implemented odometry publishing
    # When both parameters are set to true: publish_joint_states: true AND 
    # publish_odom: true - driver doesn't work
    # TODO! Fix the bug
    publish_joint_states: false
    publish_odom: false
    # ----------------------------------------

    # Based upon your particular motor gearing and encoders.
    # These values are used to scale cmd_vel commands 
    # and encoder values to motor commands and odometry, respectfully.
    quad_pulses_per_meter: 10700
    quad_pulses_per_revolution: 4385
    
    # Based upon your particular robot model.
    # The wheel separation and radius, in meters.
    wheel_radius: 0.065
    wheel_separation: 0.29
    
    
    # Topic name to be used to publish the RoboClaw status messages.
    roboclaw_status_topic: "roboclaw_status"

    # See: http://unixwiz.net/techtips/termios-vmin-vtime.html
    vmin: 1
    vtime: 2

